apiVersion: profiles.barpilot.io/v1alpha1
kind: ProfileBinding
metadata:
  name: php-deployment-binding
  namespace: default
spec:
  profileRef:
    name: php-image-update
  targetSelector:
    resourceRule:
      apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments"]
    objectSelector:
      matchLabels:
        app: php-app
    namespaces:
    - default
    - staging
  updateStrategy:
    type: Immediate
  enabled: true
