apiVersion: profiles.barpilot.io/v1alpha1
kind: ProfileBinding
metadata:
  name: php-deployment-binding
  namespace: default
spec:
  profileRef:
    name: php-image-update
  targetSelector:
    apiVersion: apps/v1
    kind: Deployment
    matchLabels:
      app: php-app
    namespaces:
    - default
    - staging
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxConcurrent: "50%"
      pauseBetweenUpdates: 30s
  enabled: true
